### ISSUE TITLE
Modifying doesn't appear to work

### ISSUE THREAD

**Issue by tgm4883** [FreekingDean/insteon-hub#6]
Using the latest git checkout as of Sep 7th, modifying doesn't appear to be working. I've tried modifying a device name, a room name, and a scene name and none appear to work. 

Using the following code I would expect the name DeviceName to change to testdevice. Line 3 does end up printing 'testdevice', however when running a second time line 1 prints the original name again. I've also tried adding a "i.devices[15].save" at line 4 but that doesn't seem to help.

```
print(i.devices[15].DeviceName)
i.devices[15].DeviceName='testdevice'
print(i.devices[15].DeviceName)
```

**Comment by FreekingDean** [comment]
Can you post the output of that code?

**Comment by tgm4883** [comment]
I'm running it from a python3 file I created in the root of the repository. 

The full code of the file is

```
#!/usr/bin/env python3

import insteon

i = insteon.Insteon("xxxxxxxxxxxxxxxxxxxx", "XXXXXXXXXXXXX", "xxxxxxxxxxxxxxxxxxxxxxxxxxx")
print(i.devices[15].DeviceName)
i.devices[15].DeviceName='testdevice'
print(i.devices[15].DeviceName)
```

So the issue presents itself when I run the file twice. Output below

```
thomas@sulley:~/code/insteon-hub$ ./run.py 
Office Switch 1
testdevice
thomas@sulley:~/code/insteon-hub$ ./run.py 
Office Switch 1
testdevice
thomas@sulley:~/code/insteon-hub$
```

**Comment by tgm4883** [comment]
Anything else you need from me on this? I've made some minor changes to my code so I could upload it here https://github.com/tgm4883/insteon-hub 

I would expect that running the run.py file twice would print the new name "testdevice1" both times instead of just the first time, but I guess I need to someone state that I want to commit the changes back up to instead (I guess I'm just changing the local variable?)

**Comment by FreekingDean** [comment]
Save is something that is still mostly unfinished. If you want to submit a PR adding functionality to finalize the `save` method on an insteon resource I would be very appreciative. I believe you only need to change:

``` python
return self._api_iface.put(base_path + resource_name + "/" + str(self._resource_id))
```

to

``` python
return self._api_iface.put(base_path + resource_name + "/" + str(self._resource_id), data=data)
```

I don't really have much time to test this right now let me know if that works.

**Comment by tgm4883** [comment]
Tried testing it and I found that it's not actually calling the save stuff at all. I added a print statement (see https://github.com/tgm4883/insteon-hub/blob/master/insteon/api.py#L147), but that never gets printed to the command line when I run run.py. Am I trying to save incorrectly? I've tried calling save, but I don't get any error message https://github.com/tgm4883/insteon-hub/blob/master/run.py#L66

**Comment by tgm4883** [comment]
Ok, decided to try something else and it now saves, however on the next run it throws an error. (I've verified the device name has been changed via the insteon android app). Here's the changes I needed to make so it will save

https://github.com/tgm4883/insteon-hub/commit/677b9d1435ac327000ff4235af5139fced2b6608

The error I get now is an API error, possibly to do with some of the changes I made?

`API error: 
Traceback (most recent call last):
  File "/home/thomas/code/insteon-hub/insteon/api.py", line 90, in all
    response = api.get(cls.base_path + cls.resource_name, {'properties':'all'})
  File "/home/thomas/code/insteon-hub/insteon/api.py", line 34, in get
    return self._check_response(response, self.get, path, data)
  File "/home/thomas/code/insteon-hub/insteon/api.py", line 64, in _check_response
    raise APIError(response.json())
insteon.api.APIError: {'message': 'There has been an internal error.', 'code': 5001}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./run.py", line 19, in <module>
    i = insteon.Insteon(username, password, apikey)
  File "/home/thomas/code/insteon-hub/insteon/insteon.py", line 23, in **init**
    self.devices = Device.all(Device, self.api)
  File "/home/thomas/code/insteon-hub/insteon/api.py", line 96, in all
    for key,value in e.data.iteritems:
AttributeError: 'dict' object has no attribute 'iteritems'`

**Comment by FreekingDean** [comment]
Looks like this has to do with the items in the resource. I am working on a fix for this now.

**Comment by FreekingDean** [comment]
This should now be totally fixed. in `0.6.1`

**Comment by tgm4883** [comment]
I've tested the changes and it's still broken. I've commented out almost all of the run.py file and it's failing still, so it seems to be somewhere in the Insteon object setup. Here's the diff between our two repos.

https://github.com/FreekingDean/insteon-hub/compare/master...tgm4883:master

**Comment by FreekingDean** [comment]
@tgm4883 Can you tell me what lines aren't working & the error message you are getting. I see in your `run.py` file all the relevant lines are commented out. https://github.com/tgm4883/insteon-hub/blob/71735a80886f8923f7574da8f17256090dd00505/run.py

**Comment by tgm4883** [comment]
@FreekingDean That's why this is so weird. I'm running the run.py file just as it's in the repo, with everything commented out except lines 11-19. I just attempted to clear out all the pyc and **pycache** directory but I get the same result. Commenting out line 19 resolves the issue, so it's definitely something with that. I'd also add that this all started when I renamed one of the devices (lines 65-68 I think)

thomas@sulley:~/code/insteon-hub$ ./run.py 
API error: 
Traceback (most recent call last):
  File "/home/thomas/code/insteon-hub/insteon/api.py", line 90, in all
    response = api.get(cls.base_path + cls.resource_name, {'properties':'all'})
  File "/home/thomas/code/insteon-hub/insteon/api.py", line 34, in get
    return self._check_response(response, self.get, path, data)
  File "/home/thomas/code/insteon-hub/insteon/api.py", line 64, in _check_response
    raise APIError(response.json())
insteon.api.APIError: {'message': 'There has been an internal error.', 'code': 5001}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./run.py", line 19, in <module>
    i = insteon.Insteon(username, password, apikey)
  File "/home/thomas/code/insteon-hub/insteon/insteon.py", line 23, in **init**
    self.devices = Device.all(Device, self.api)
  File "/home/thomas/code/insteon-hub/insteon/api.py", line 96, in all
    for key,value in e.data.iteritems:
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by FreekingDean** [comment]
@tgm4883 That is all due to your added use of the scene and house stuffs. They are not fully implemented yet.

**Comment by FreekingDean** [comment]
scenes & rooms **

**Comment by FreekingDean** [comment]
During your call to all, it is looking for them as well. They are not implemented.

**Comment by tgm4883** [comment]
@FreekingDean Not sure why that wasn't updated in the repo, but I've commented those out to test. Getting the same error (just pushed all my changes to the repo, these are the only differences between our repos)  https://github.com/FreekingDean/insteon-hub/compare/master...tgm4883:master

**Comment by FreekingDean** [comment]
I cloned your code, it worked completly. I would make sure you are:
- Using python3 (if python2.7 is your default)
- That you pip install insteon-hub --upgrade OR pip uninstall insteon-hub (use pip3 if you need to)

**Comment by tgm4883** [comment]
I didn't have insteon-hub installed, I was calling the code directly from the source directory. I've now installed it and have the same issue.

Is it possible something is screwed up in my insteon account? 5001 is an insteon error, is there some way we can step through the API calls and see which one is causing that error message?

**Comment by FreekingDean** [comment]
There are python debuggers, though I am not familiar with them. Are you running python 3 or 2.7 as your default? try running your `run.py` file with `python3 run.py`

**Comment by tgm4883** [comment]
I was just running ./run.py which I thought due to line 1 would run it as python 3. I've just tried it by 'python3 run.py' and I get the same error.

**Comment by tgm4883** [comment]
@FreekingDean Ok, I put in a bunch of print statements to see what was happening, did some more testing and I have a theory as to what is happening.

I don't believe there is an issue in the insteon-hub code per se, but an issue in that there is no error checking when saving things to Insteon. This is what I ended up having to do to fix this error I was getting.

First, I deleted the device that I had renamed (it's important to note that it is a Keypadlinc) from my Insteon Hub via the Android app. Upon readding the device, it added it as a switch with device details of x00x00x00 (I'm assuming switch is some default). I needed to remove the device from the hub again, do a factory reset on the keypadlinc then readd it. Now it's showing up as a Keypadlinc again and I can control it. My run.py script also works again and I can query the device names (although I haven't tried to rename the device again).

So I think there's a larger issue here that needs to be addressed, although ideally it needs to be addressed on the Insteon API side to not allow things to be written without a default set of items (I believe it's a Insteon issue due to the x00x00x00 issue, but perhaps the insteon-hub code writes that when there isn't one specified).

I'm up for testing any new code you think might resolve issues like this from happening in the future.

**Comment by FreekingDean** [comment]
This should no longer happen. Because we were testing with mostly in development code side effects like this can happen. If the code is working from here on I would say this is fixed and we can close this issue. I don't have a ton of time to put into validating inputs, I will leave that up to the user of this library :)
